In [1]:
import torch 
import torch.nn.functional as F
from torch import nn

## 构造一个没有任何参数的层

In [2]:
class CenteredLayer(nn.Module):
    """此处是自定义层，和自定义网络类似咯"""
    def __init__(self) -> None:
        super().__init__()
        
    def forward(self, X):
        return X - X.mean()

layer = CenteredLayer()
X = torch.Tensor([1,2,3,4,5])
layer(X)

tensor([-2., -1.,  0.,  1.,  2.])

将层作为组件合并到构建更复杂的网络当中

In [6]:
net = nn.Sequential(nn.Linear(8, 126), CenteredLayer())
Y = net(torch.rand(4, 8))


tensor(-9.4611e-10, grad_fn=<MeanBackward0>)

## 构造一个带有参数的层<br>
这些参数可以通过训练进行调整

In [17]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units) -> None: # 输入数和输出数
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units)) # 随机初始化参数后放入Parameter中，自动加入梯度什么的
        self.bias = nn.Parameter(torch.randn(units))
    
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data # 注意用data取到实际值
        return F.relu(linear)

model = MyLinear(5, 3)
# 使用自定义层直接进行前向传播计算
X = torch.rand(2,5)
model(X)

tensor([[1.2815, 0.0000, 0.0797],
        [0.2958, 0.0000, 0.0000]])

In [10]:
# # nn.Parameter()用法
# test = torch.randn(2, 3)
# display(test)
# display(nn.Parameter(test)) # 可见的也就是加个梯度

tensor([[-1.0241,  0.3363,  0.3220],
        [-0.8959, -0.4160, -0.3392]])

Parameter containing:
tensor([[-1.0241,  0.3363,  0.3220],
        [-0.8959, -0.4160, -0.3392]], requires_grad=True)