实现池化层的正向传播

In [1]:
import torch 
from torch import nn
from d2l import torch as d2l

In [6]:
def pool2d(X, pool_size, mode='max'):
    p_h, p_w = pool_size # 池化尺寸
    Y = torch.zeros(X.shape[0] - p_h + 1, X.shape[1]- p_w + 1) # 初始化输出
    for i in range(Y.shape[0]):
        for j in range(Y.shape[0]):
            if mode == 'max':
                Y[i, j] = X[i:i+p_h, j:j+p_w].max()
            elif mode == 'avg':
                Y[i, j] = X[i:i+p_h, j:j+p_w].mean()
    return Y

验证

In [15]:
X = torch.arange(9).float().reshape(3,3)
pool2d(X, (2,2)), pool2d(X, (2,2), mode='avg')

(tensor([[4., 5.],
         [7., 8.]]),
 tensor([[2., 3.],
         [5., 6.]]))

填充与步幅

In [16]:
X = torch.arange(16, dtype=torch.float32).reshape((1,1,4,4))
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

注意奥：PyTorch框架中的步幅与池化窗口的大小相同 即窗口之间是不重叠的

In [17]:
pool2d = nn.MaxPool2d(3) # 3*3 stride=3*3 故结果只有一个值
pool2d(X)

tensor([[[[10.]]]])

In [18]:
pool2d_ =nn.MaxPool2d(2) # 这样的话就有四个值
pool2d_(X) 

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

当然你可以手动指定

In [19]:
pool2d__ = nn.MaxPool2d(kernel_size=2, stride=1, padding=1) # 4+1*2-2+1 = 5
pool2d__(X)

tensor([[[[ 0.,  1.,  2.,  3.,  3.],
          [ 4.,  5.,  6.,  7.,  7.],
          [ 8.,  9., 10., 11., 11.],
          [12., 13., 14., 15., 15.],
          [12., 13., 14., 15., 15.]]]])